/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteRouteImport } from './routes/catalog/route'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogObjectsObjectIdRouteRouteImport } from './routes/catalog/objects.$objectId/route'
import { Route as CatalogObjectsObjectIdIndexRouteImport } from './routes/catalog/objects.$objectId/index'
import { Route as CatalogObjectsObjectIdModelsNewRouteImport } from './routes/catalog/objects.$objectId/models.new'
import { Route as CatalogObjectsObjectIdModelsModelNameEditRouteImport } from './routes/catalog/objects.$objectId/models.$modelName.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRouteRoute = CatalogRouteRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRouteRoute,
} as any)
const CatalogObjectsObjectIdRouteRoute =
  CatalogObjectsObjectIdRouteRouteImport.update({
    id: '/objects/$objectId',
    path: '/objects/$objectId',
    getParentRoute: () => CatalogRouteRoute,
  } as any)
const CatalogObjectsObjectIdIndexRoute =
  CatalogObjectsObjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CatalogObjectsObjectIdRouteRoute,
  } as any)
const CatalogObjectsObjectIdModelsNewRoute =
  CatalogObjectsObjectIdModelsNewRouteImport.update({
    id: '/models/new',
    path: '/models/new',
    getParentRoute: () => CatalogObjectsObjectIdRouteRoute,
  } as any)
const CatalogObjectsObjectIdModelsModelNameEditRoute =
  CatalogObjectsObjectIdModelsModelNameEditRouteImport.update({
    id: '/models/$modelName/edit',
    path: '/models/$modelName/edit',
    getParentRoute: () => CatalogObjectsObjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/objects/$objectId': typeof CatalogObjectsObjectIdRouteRouteWithChildren
  '/catalog/objects/$objectId/': typeof CatalogObjectsObjectIdIndexRoute
  '/catalog/objects/$objectId/models/new': typeof CatalogObjectsObjectIdModelsNewRoute
  '/catalog/objects/$objectId/models/$modelName/edit': typeof CatalogObjectsObjectIdModelsModelNameEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/permissions': typeof PermissionsRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/objects/$objectId': typeof CatalogObjectsObjectIdIndexRoute
  '/catalog/objects/$objectId/models/new': typeof CatalogObjectsObjectIdModelsNewRoute
  '/catalog/objects/$objectId/models/$modelName/edit': typeof CatalogObjectsObjectIdModelsModelNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/objects/$objectId': typeof CatalogObjectsObjectIdRouteRouteWithChildren
  '/catalog/objects/$objectId/': typeof CatalogObjectsObjectIdIndexRoute
  '/catalog/objects/$objectId/models/new': typeof CatalogObjectsObjectIdModelsNewRoute
  '/catalog/objects/$objectId/models/$modelName/edit': typeof CatalogObjectsObjectIdModelsModelNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/permissions'
    | '/catalog/'
    | '/catalog/objects/$objectId'
    | '/catalog/objects/$objectId/'
    | '/catalog/objects/$objectId/models/new'
    | '/catalog/objects/$objectId/models/$modelName/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/permissions'
    | '/catalog'
    | '/catalog/objects/$objectId'
    | '/catalog/objects/$objectId/models/new'
    | '/catalog/objects/$objectId/models/$modelName/edit'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/permissions'
    | '/catalog/'
    | '/catalog/objects/$objectId'
    | '/catalog/objects/$objectId/'
    | '/catalog/objects/$objectId/models/new'
    | '/catalog/objects/$objectId/models/$modelName/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRouteRoute: typeof CatalogRouteRouteWithChildren
  PermissionsRoute: typeof PermissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/catalog/objects/$objectId': {
      id: '/catalog/objects/$objectId'
      path: '/objects/$objectId'
      fullPath: '/catalog/objects/$objectId'
      preLoaderRoute: typeof CatalogObjectsObjectIdRouteRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/catalog/objects/$objectId/': {
      id: '/catalog/objects/$objectId/'
      path: '/'
      fullPath: '/catalog/objects/$objectId/'
      preLoaderRoute: typeof CatalogObjectsObjectIdIndexRouteImport
      parentRoute: typeof CatalogObjectsObjectIdRouteRoute
    }
    '/catalog/objects/$objectId/models/new': {
      id: '/catalog/objects/$objectId/models/new'
      path: '/models/new'
      fullPath: '/catalog/objects/$objectId/models/new'
      preLoaderRoute: typeof CatalogObjectsObjectIdModelsNewRouteImport
      parentRoute: typeof CatalogObjectsObjectIdRouteRoute
    }
    '/catalog/objects/$objectId/models/$modelName/edit': {
      id: '/catalog/objects/$objectId/models/$modelName/edit'
      path: '/models/$modelName/edit'
      fullPath: '/catalog/objects/$objectId/models/$modelName/edit'
      preLoaderRoute: typeof CatalogObjectsObjectIdModelsModelNameEditRouteImport
      parentRoute: typeof CatalogObjectsObjectIdRouteRoute
    }
  }
}

interface CatalogObjectsObjectIdRouteRouteChildren {
  CatalogObjectsObjectIdIndexRoute: typeof CatalogObjectsObjectIdIndexRoute
  CatalogObjectsObjectIdModelsNewRoute: typeof CatalogObjectsObjectIdModelsNewRoute
  CatalogObjectsObjectIdModelsModelNameEditRoute: typeof CatalogObjectsObjectIdModelsModelNameEditRoute
}

const CatalogObjectsObjectIdRouteRouteChildren: CatalogObjectsObjectIdRouteRouteChildren =
  {
    CatalogObjectsObjectIdIndexRoute: CatalogObjectsObjectIdIndexRoute,
    CatalogObjectsObjectIdModelsNewRoute: CatalogObjectsObjectIdModelsNewRoute,
    CatalogObjectsObjectIdModelsModelNameEditRoute:
      CatalogObjectsObjectIdModelsModelNameEditRoute,
  }

const CatalogObjectsObjectIdRouteRouteWithChildren =
  CatalogObjectsObjectIdRouteRoute._addFileChildren(
    CatalogObjectsObjectIdRouteRouteChildren,
  )

interface CatalogRouteRouteChildren {
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogObjectsObjectIdRouteRoute: typeof CatalogObjectsObjectIdRouteRouteWithChildren
}

const CatalogRouteRouteChildren: CatalogRouteRouteChildren = {
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogObjectsObjectIdRouteRoute:
    CatalogObjectsObjectIdRouteRouteWithChildren,
}

const CatalogRouteRouteWithChildren = CatalogRouteRoute._addFileChildren(
  CatalogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRouteRoute: CatalogRouteRouteWithChildren,
  PermissionsRoute: PermissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
