import type { Tree } from '@nx/devkit';
import type { ContextNames } from './options';

const GITLAB_CI = '.gitlab-ci.yml';

export function ensureContextCi(tree: Tree, context: ContextNames): boolean {
  const ciPath = `.gitlab/ci/contexts/${context.name}.yml`;
  if (tree.exists(ciPath)) {
    return false;
  }

  tree.write(ciPath, renderContextCi(context, ciPath));
  includeContextCi(tree, ciPath);

  return true;
}

function renderContextCi(context: ContextNames, ciPath: string): string {
  const { name, bffProject, webProject, bffRoot, webRoot, contractRoot } =
    context;

  return `# Generated by @jarvis/nx-plugin; edit the changes: lists when this context's imports change.

.${name}-changes:
  bff: &bff-changes
    - ${bffRoot}/**/*
    - ${contractRoot}/**/*
    - libs/db/**/*
    - libs/logging/**/*
    - charts/**/*
    - ${ciPath}
    - pnpm-lock.yaml
  web: &web-changes
    - ${webRoot}/**/*
    - ${bffRoot}/src/router.ts
    - ${bffRoot}/src/trpc.ts
    - ${bffRoot}/src/**/*.router.ts
    - ${contractRoot}/**/*
    - libs/ui/**/*
    - libs/db/**/*
    - libs/logging/**/*
    - charts/**/*
    - ${ciPath}
    - pnpm-lock.yaml

build-${name}-bff:
  extends: .build
  variables:
    PROJECT: '${bffProject}'
    PROJECT_PATH: ${bffRoot}
    IMAGE_NAME: ${name}-bff
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: *bff-changes
    - if: $CI_COMMIT_TAG

build-${name}-web:
  extends: .build
  variables:
    PROJECT: '${webProject}'
    PROJECT_PATH: ${webRoot}
    IMAGE_NAME: ${name}-web
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: *web-changes
    - if: $CI_COMMIT_TAG

deploy-${name}-bff:
  extends: .deploy
  needs: [verify, build-${name}-bff]
  variables:
    RELEASE: ${name}-bff
    SECRET: 'true'
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: *bff-changes
      when: manual
      allow_failure: false
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: false

deploy-${name}-web:
  extends: .deploy
  needs: [verify, build-${name}-web]
  variables:
    RELEASE: ${name}-web
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: *web-changes
      when: manual
      allow_failure: false
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: false
`;
}

function includeContextCi(tree: Tree, ciPath: string): boolean {
  if (!tree.exists(GITLAB_CI)) {
    return false;
  }

  const source = tree.read(GITLAB_CI, 'utf-8');
  if (!source) {
    return false;
  }

  const line = `  - local: ${ciPath}`;
  if (source.includes(line)) {
    return false;
  }

  const block = /^(include:\n(?: {2}- local: .*\n)+)/m;
  if (!block.test(source)) {
    return false;
  }

  tree.write(
    GITLAB_CI,
    source.replace(block, (match) => `${match}${line}\n`),
  );

  return true;
}
